### ISSUE TITLE
ENOENT: no such file or directory

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/storjshare-gui#410]
### Versions

Replace the values below with your own:
- **GUI Version:** 2.0.10
- **Operating System:** Windows 10
### Actual Behavior

![2016-10-17](https://cloud.githubusercontent.com/assets/11735738/19455086/f9526020-94bb-11e6-96a4-241017f9f505.png)

After this it goes into preparing, i can reload and start it again, but it will go into preparing again after a few minutes, even with allot of peers.

![2016-10-17 1](https://cloud.githubusercontent.com/assets/11735738/19455398/2af27de4-94bd-11e6-9f29-6a25945c5d4f.png)
### Logs

[logs.zip](https://github.com/Storj/storjshare-gui/files/534707/logs.zip)
### Steps to Reproduce

Run the GUI for a few hours.
### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by aleitner** [comment]
This should be resolved with the 2.0.11 release. If not I'll reopen this issue

**Comment by MeijeSibbel** [comment]
Error still occurs in latest GUI release, please reopen it @aleitner . GUI: 2.1.11
